### ISSUE TITLE
De-dupe results when using multiple relays

### ISSUE THREAD

**Issue by jb55** [blakejakopovic/nostcat#2]
Once we support multiple relays (#1) it would be nice to have an option to de-duplicate results.

**Comment by blakejakopovic** [comment]
Same as #1, this should be working as of v0.3.0. Let me know how you go.

Sort and unique results with multiple servers (dedupe)
```shell
$ echo '["REQ", "RAND", {"kinds": [1], "limit": 8}]' |
  nostcat --unique wss://relay.damus.io wss://nostr.ono.re
```
